apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sample-angular-app
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: sample-angular-app
    spec:
      containers:
      - name: sample-angular-app
        image: sourabh385/myapp:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sample-angular-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: sample-angular-app
